# ============================================================================
# .pre-commit-config.yaml - Git Pre-commit Hooks (Fixed)
# ============================================================================
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        language_version: python3
        args: ['--line-length=127']

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ['--max-line-length=127', '--extend-ignore=E203,W503,E501']

  # MyPy ist optional - auskommentiert für bessere Performance
  # Falls Sie Type Checking wünschen, kommentieren Sie dies ein:
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.11.2
  #   hooks:
  #     - id: mypy
  #       args: [--ignore-missing-imports, --no-strict-optional]
  #       additional_dependencies: []
