name: koeln-library-search
channels:
  - conda-forge
  - defaults
dependencies:
  # Python Version
  - python=3.9
  
  # Web Scraping und HTTP Requests
  - requests=2.31.*
  - beautifulsoup4=4.12.*
  - lxml=4.9.*
  - html5lib=1.1
  
  # URL und Text Verarbeitung
  - urllib3=2.0.*
  - chardet=5.2.*
  
  # Zusätzliche nützliche Packages für Web Scraping
  - selenium=4.15.*  # Falls JavaScript-Heavy Seiten
  - fake-useragent=1.4.*  # Für realistische User-Agents
  
  # Data Handling (falls erweiterte Funktionen gewünscht)
  # - pandas=2.1.*
  # - numpy=1.24.*
  
  # Logging und Debugging
  - colorama=0.4.*  # Für farbige Konsolenausgaben
  
  # Optional: Jupyter für interaktive Entwicklung
  # - jupyter=1.0.*
  # - ipykernel=6.25.*
  
  # Weitere hilfreiche Tools
  - tqdm=4.66.*  # Progress bars
  - python-dateutil=2.8.*
  
  # Pip packages (falls nicht über conda verfügbar)
  - pip
  - pip:
    - requests-html  # Alternative für JavaScript-Heavy Sites
    # - playwright  # Modern web automation (optional)

# Entwicklungsumgebung (optional - kann auskommentiert werden)
# - pytest=7.4.*
# - pytest-cov=4.1.*
# - black=23.9.*
# - flake8=6.1.*