name: Auto Versioning & Badges
on:
  push:
    branches:
      - master
      - main

jobs:
  versioning-and-badges:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Auto Versioning
        uses: dgaida/auto-version-action/auto-version@main

      - name: Add Badges
        uses: dgaida/auto-version-action@main
