name: Documentation

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**.md'
      - 'docs/**'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**.md'
      - 'docs/**'

jobs:
  docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check Markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          config-file: '.github/markdown-link-check-config.json'
      
      - name: Validate README
        run: |
          if [ -f README.md ]; then
            echo "✅ README.md exists"
            if [ $(wc -l < README.md) -lt 10 ]; then
              echo "❌ README.md too short"
              exit 1
            fi
          else
            echo "❌ README.md missing"
            exit 1
          fi
          