# ============================================================================
# .github/workflows/lint.yml
# ============================================================================
name: Code Quality

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**.py'
      - '.flake8'
      - '.pylintrc'
      - 'pyproject.toml'
      - '.github/workflows/lint.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**.py'
      - '.flake8'
      - '.pylintrc'
      - 'pyproject.toml'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black mypy pylint

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Check formatting with Black
        run: |
          black --check --diff .

      - name: Type check with mypy
        run: |
          mypy . --ignore-missing-imports --no-strict-optional
        continue-on-error: true
